version: '3.8'

networks:
  backend:

services:
  # --- Сервис PostgreSQL ---
  postgres_db:
    image: postgres:14
    container_name: gpt_postgres
    restart: always
    environment:
      POSTGRES_DB: gpt_db
      POSTGRES_USER: gpt_user
      POSTGRES_PASSWORD: gpt_password
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- Сервис Qdrant (если используется) ---
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    restart: always
    ports:
      - "6333:6333"  # REST API
      - "6334:6334"  # gRPC
    networks:
      - backend

  # --- Telegram бот ---
  telegram_bot:
    build: ./telegram
    container_name: bot
    restart: always
    depends_on:
      - postgres_db
      - qdrant
      - api_gpt  # бот дождется готовности сервиса api_gpt
    environment:
      # Параметры для подключения к базе (если бот к ней обращается напрямую)
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: gpt_db
      DB_USER: gpt_user
      DB_PASSWORD: gpt_password
    volumes:
      # Здесь мы монтируем секреты как файлы:
      - ./secrets/telegram_token:/run/secrets/telegram_token:ro
      - ./secrets/gpt_api_url:/run/secrets/gpt_api_url:ro
      - ./secrets/summary_api_url:/run/secrets/summary_api_url:ro
    networks:
      - backend

  # --- Сервис с FastAPI (GPT API) ---
  api_gpt:
    build: ./api_gpt
    container_name: gpt_api
    restart: always
    depends_on:
      - postgres_db  # подождать, пока postgres_db будет готов
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      # Обязательно прописываем, чтобы код смог подключиться к базе
      DB_HOST: postgres_db
      DB_PORT: 5432
      DB_NAME: gpt_db
      DB_USER: gpt_user
      DB_PASSWORD: gpt_password
      # При желании, можно экспортировать и GPT_API_KEY из env, или через файл
      # GPT_API_KEY: "значение_ключа"
    volumes:
      # Секрет (ключ GPT) монтируется как файл /run/secrets/gpt_api_key
      - ./secrets/gpt_api_key:/run/secrets/gpt_api_key:ro
    ports:
      - "9001:9001"  # Пробрасываем порт API наружу
    networks:
      - backend

volumes:
  postgres_data:
