version: '3.8'

networks:
  backend:

services:
  api_gpt:
    hostname: gpt_api
    container_name: gpt_api
    build: api_gpt/
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - ./data:/opt/api/data
    logging:
      options:
        max-size: 50m
    networks:
      - backend

  telegram:
    hostname: bot
    container_name: bot
    build: telegram/
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - PYTHONUNBUFFERED=1
    restart: always
    ipc: host
    logging:
      options:
        max-size: 50m
    networks:
      - backend
